remote_theme: mmistakes/minimal-mistakes@4.27.1

title: Nidaa Mungloo
description: Senior Software Engineer Blog
minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache

author:
  name   : "Nidaa Mungloo"
  avatar : "/assets/nidaa.jpeg"
  bio    : "Senior Software Engineer based in Berlin"

logo: "/assets/logo.png"
  
navigation:
  - name: "main"
    items:
      - title: "Blog"
        url: /blog/
      - title: "Projects"
        url: /projects/  
      - title: "About"
        url: /about/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
   - scope:
      path: ""
      type: "pages"
    values:
      css: /assets/css/custom.css

url: "https://www.nidaamungloo.com"
repository: nida28/personal-site
